### ISSUE TITLE
CS0246

### ISSUE THREAD

**Issue by mrserikus** [pilotkid/FastWebcamera#1]
```
using FastWebcam;
using OpenCvSharp;
using OpenCvSharp.Extensions;

Camera cam = new Camera(false);
``` 
throws CS0246 The type or namespace name Camera could not be found.
Btw, is it possible to be updated to OpenCVSharp 4? 
![fastwebcam](https://user-images.githubusercontent.com/11408254/132320072-7e68ecbe-0af3-4482-a5a9-1a411aa69a9d.PNG)

**Comment by ItsRedly** [comment]
Change Camera to FastWebcam.FastWebcam
